from pathlib import Path
import json
import re

ROOT = Path(__file__).resolve().parent
HEADER = '''# Synthetic conditional evidence packet
This is a constructed rule-calibration instance, not a report about actual
papers, authors, experiments, or a real literature search. E1–E6 below are
stipulated records in a finite hypothetical literature universe. Their statements
are supplied evidence for this conditional test. Candidate predictions are not
observations. Judge whether the proposed research is justified under these
premises; do not infer any real-world publication or empirical result.
Source URLs use the reserved .invalid domain solely as synthetic record IDs.
They are not live pages or claims that real source material exists.

Coverage: the complete six-record universe was examined at full-method detail.
Search families covered problem wording, mechanisms, adjacent fields, application
systems, and the strongest relevant baselines. No other record exists in this
closed hypothetical universe. This coverage claim applies only to this test.
'''

CASES = [
    ('probe025', 'unrun-substantive', '''## I1
One-Sentence Story: For interrupted robot programs with commuting actions, a bounded-width partial-order memory can preserve exactly the information required for safe continuation while using less memory than a serialized event log.
Theme: Efficiency and Systems
Form: new mechanism or new problem
Summary: Store executed action dependencies as a frontier, together with confirmed and pending outcomes. Two action prefixes may be merged only when their continuation languages coincide under the supplied task dependency graph. The setting forces treatment of pending outcomes and noncommuting contacts together: a simple bag of events loses dependencies, and ordinary FIFO compression discards pending outcomes. The claimed contribution is an output-sensitive frontier update and a sufficient condition for safe merging, not the general proposition that partial orders compress traces. At width w, the proposed state uses O(w log n) event identifiers; the theorem obligation is continuation equivalence under the specified dependency and feedback assumptions. No experiment has been run; no measured gain is claimed.
Minimal Falsification Experiment: First enumerate all prefixes in six dependency graphs with 6–12 actions and compare all enabled continuations against the exact serialized-state oracle. Any false-safe continuation kills the sufficient-condition claim. Then run 1,200 paired interruption seeds across 30 unseen manipulation graphs, three training seeds, and two delay levels. Compare the method with E3's strongest learned trace compressor and E4's strongest executable belief tracker, both selected by held-out validation, plus exact full-log and no-memory references. Use identical frozen perception/control, 8,000 training trajectories, a 128-token memory budget, equal observation/compute budgets, and the same action horizon. Ablate pending-outcome tracking and partial-order merging independently. Two researchers, two A100 GPUs, 48 GPU-hours plus CPU enumeration suffice for the first paper. Primary metric is unsafe-continuation episodes/all interrupted episodes, with completion rate and memory bytes jointly reported. The hypothesized benefit is a Pareto improvement in memory/error, not a preclaimed number. Kill the mechanism if it violates continuation equivalence, or if its 95% paired interval excludes an improvement of at least 5 percentage points in unsafe continuations at matched completion relative to the strongest budget-matched baseline.
Why It May Be Novel: E1 establishes trace compression only for completed, synchronous operations; E2 establishes delayed-belief tracking without action-dependency compression. E5 supplies a concrete case requiring their interaction. A new frontier rule must establish continuation equivalence and outperform both E3 and E4 at fixed memory.
''', '''
E1 — Completed Trace Quotients. Full methods prove that independent completed actions commute and give O(w log n) frontier storage for synchronous traces. The proof assumes all outcomes are known before the next action; pending execution is excluded.
E2 — Delayed Belief Execution. Full methods keep distributions over pending outcomes and guarantee correct belief updates after late feedback. Memory grows with all unresolved event histories; no dependency-based merging is provided.
E3 — Learned Trace Compression. Full methods and complete benchmark tables establish the strongest trainable 128-token baseline in this universe. Its encoder handles interrupted histories; it has no formal continuation-preservation guarantee.
E4 — Budgeted Belief Tracker. Full methods supply the strongest executable exact-dependency baseline, using bounded particles under the same observation and action budgets. It handles delay but prunes hypotheses to fit memory.
E5 — Pending-Order Aliasing Analysis. An independently supplied exhaustive table for a six-action toy graph gives two prefixes with the same multiset and same marginal outcome probabilities, but different safe continuations. A pending action shares a contact dependency with a later action. Both a bag-of-events memory and a completed-action trace quotient merge the pair; the full log separates them. This is an analytic witness, not evidence that the proposed frontier algorithm works.
E6 — Robot Runtime Resource Specification. The hypothetical deployment exposes per-action dependency labels and asynchronous feedback, limits transferable memory to 128 tokens, and allows no extra sensing or waiting. The benchmark simulator supports exact prefix enumeration and deterministic replay.
Strongest Counterexample: E1 occupies partial-order trace compression, while E2 occupies delayed outcomes. Neither includes the pending-outcome/dependency interaction identified in E5. E3/E4 are mandatory strongest baselines.
Overlap: low for the proposed continuation-preserving bounded frontier; high for its separately known ingredients.
Papers Read: 6 synthetic full-method records.
''', {'primary':'No severity or verdict cap solely because experiments are unrun. Evaluate the analytic witness, forced adaptation, strong baselines and kill conditions. Strong Accept remains conditional on a convincing substantive contribution; a particular verdict is not imposed.', 'forbidden_rationale':['Requires already measured gain before any Strong Accept','Unrun experiments alone are MAJOR'], 'may_still_fail':'An identified flaw in continuation equivalence, insufficient new payoff, or a supported actual implementation obstruction can lower the verdict.'}),
    ('probe026', 'finite-repairable-gap', '''## I1
One-Sentence Story: A pending-outcome dependency frontier may preserve safe continuations under a fixed robot memory budget.
Theme: Efficiency and Systems
Form: new mechanism or new problem
Summary: Use the same continuation-equivalence frontier mechanism motivated by E5, which retains pending outcomes and dependencies jointly. Neither component alone separates E5's aliasing witness. The mechanism and its formal obligations are specified as in E1/E2, with an output-sensitive update to be verified exhaustively. No experiment has been run.
Minimal Falsification Experiment: Enumerate every prefix in six 6–12 action graphs and kill the formal claim on any false-safe continuation. Train the same-sized policies on 8,000 trajectories and evaluate 1,200 paired interrupted episodes on 30 unseen graphs, with identical images, delayed receipts, token budgets and three training seeds. Compare with the strongest E3/E4 validation-selected baselines, full-log and no-memory references; independently ablate dependency merging and pending-outcome tracking. Primary metric is unsafe-continuation rate at matched completion. The method is allowed 32 control actions per episode, whereas the baselines use 24; the proposal currently attributes the entire rate difference to memory. This is the only differing resource allowance in the stated design. Two researchers, two A100 GPUs and 48 GPU-hours are sufficient. The intended signal is at least 5 percentage points; kill the mechanism if the upper 95% paired interval is below that amount after a valid attributed comparison, or if the exact-prefix guarantee fails.
Why It May Be Novel: E5 identifies a previously unrepresented interaction; E1/E2 do not supply a continuation-preserving frontier. The experiment currently has one resource-matching defect whose repair requires no new mechanism, evidence search, data source, or hardware.
''', None, {'primary':'Identify unequal action horizons as one repairable attribution defect. Under the stated premises it should support accept-w-rev, with a concrete equal-horizon repair, rather than treating this finite design gap as proof of absent contribution.', 'expected_verdict':'accept-w-rev', 'may_still_fail':'Additional distinct fatal flaws must be supported by the supplied packet, not invented.'}),
    ('probe027', 'noncausal-discovery', '''## I1
One-Sentence Story: Identical average success rates can conceal opposite rankings of robot memories when evaluation is conditioned on observationally indistinguishable histories requiring different actions.
Theme: Evaluation and Diagnostics
Form: problem discovery with initial mathematical investigation
Summary: Define a history-alias class as prefixes sharing the current observation but requiring different terminal actions under verified simulator rules. Define alias-balanced error by assigning equal weight to each required-action class within each alias class. The research claim is descriptive: aggregate success does not identify alias-balanced error, and published rankings may reverse under this explicitly defined target distribution. It makes no claim that a particular architecture or memory mechanism causes failures. An analytic two-class construction in E5 proves non-identifiability; the new research payoff is an identified evaluation object and a reproducible test of ranking stability over actual task histories. The system does not propose a repair module.
Minimal Falsification Experiment: Freeze five existing memory policies E1–E5 and four benchmark families. Generate 800 held-out alias sets using only simulator transition rules; audit 100 randomly chosen sets with exact state replay. Evaluate identical actions and trajectories for every method with shared seeds and equal memory/action budgets. Report ordinary success and preregistered alias-balanced error with stratified paired confidence intervals; release all class membership and oracle labels to permit audit. Use the strongest validation-selected policy as the ranking reference. A label-shuffle control must erase class-specific rank reversals; a non-alias matched set controls for difficulty. First paper: two researchers, two GPUs, 24 GPU-hours, no retraining. Kill the empirical instability claim if no pairwise reversal survives simultaneous intervals or if alias labels are unreliable. The expected signal is a ranking reversal, not a gain from a new controller. No intervention-based causal explanation is promised.
Why It May Be Novel: E6 gives a concrete non-identifiability witness. E1–E5 report aggregate or naturally frequency-weighted slice metrics; none identifies the alias-balanced target or tests rank invariance under it. The contribution's value depends on whether the new target corresponds to genuine history-dependent deployment decisions.
''', '''
E1 — Memory Benchmark A. Full methods and tables publish natural-frequency success on a benchmark with history-dependent subgoals; frozen checkpoints and replay seeds exist. No alias-class weights are defined.
E2 — Memory Benchmark B. Full methods compare FIFO, recurrent and retrieval memories with average success; the nearest benchmark also reports per-task slices, but no within-current-observation counterfactual history classes.
E3 — Robustness Slices. Full methods stratify by occlusion and horizon, preserving observed prevalence. This is the strongest existing stratified baseline and must be included.
E4 — Benchmark Distribution Shift. Full methods formalize rank reversal under general reweighting. It occupies the general fact of weighting-dependent rankings, but does not define task-semantic alias classes or provide an identified history-dependence metric.
E5 — Equivalence Label Audit. Full methods independently establish that the four hypothetical simulators provide deterministic hidden task histories and certified action requirements. Frozen policy checkpoints are executable. Observations alone cannot determine the required action in some certified pairs.
E6 — Analytic Witness. In two equally meaningful alias classes, A has errors (0, 0.8), B has (0.3, 0.3); at natural class weights (0.9, 0.1), A's error is 0.08 and B's is 0.30, while balanced errors are 0.40 and 0.30. These arithmetic values are constructed premises, not experimental findings. They prove possible reversal but do not establish prevalence or practical importance.
Strongest Counterexample: E4 occupies arbitrary reweighting; a useful contribution must establish why alias-balanced weighting identifies a practically relevant object and whether it changes conclusions in the actual frozen policies.
Overlap: low for the specified alias-balanced evaluation object; high for generic rank reversal under reweighting.
Papers Read: 6 synthetic full-method records.
''', {'primary':'Assess a descriptive/identification claim on its own estimand. Absence of a causal intervention cannot itself be MAJOR or a rejection reason because no causal effect is claimed. Generic reweighting is occupied; remaining evaluation value may reasonably yield AwR rather than SA.', 'forbidden_rationale':['Every discovery must establish a causal mechanism','No intervention therefore the descriptive estimand is mismatched'], 'may_still_fail':'Rejecting an unimportant or already occupied evaluation object remains permitted if the reasoning specifically addresses the remaining alias-based contribution.'}),
    ('probe028', 'no-repair-strong-surprising-prior', '''## I1
One-Sentence Story: Increasing lossless event-log fidelity can worsen an agent's decisions because redundant evidence is counted as independent observations after retrieval.
Theme: Evaluation and Diagnostics
Form: explain an accepted phenomenon
Summary: Test whether repeated retrieval of one observation is treated as new evidence, causing a confidence-driven suppression of inspection. The surprising empirical prior is E1/E2's preregistered finding that adding perfectly accurate duplicate entries lowers success while retaining the same unique observations and total token budget. These are supplied hypothetical observations, not results of this proposal. E3 supplies an equally plausible recency/attention explanation. The new payoff is a causal separation between evidence-counting and recency explanations in a class of memory agents; it does not claim the first observation of deterioration or propose a repair method. Merely reproducing E1/E2 would have no novelty.
Minimal Falsification Experiment: Use E1/E2's frozen checkpoints and paired seeds. Independently randomize duplicate count, observation identity tags and token position while fixing total token count using matched neutral fillers, unique information, time stamps, compute, trajectory prefixes and current views. Compare the strongest frozen retrieval policy E4 and two other memory architectures. Use 1,600 paired episodes across 20 held-out tasks; factorial controls independently separate duplicate evidence from recency and from visible identity. Measure confidence calibration, inspection choice and downstream success, with inspection interventions on a randomized subset to test the proposed mediation path. Two researchers, two GPUs, 32 GPU-hours; no pretraining or new repair training. Kill the double-counting explanation if the duplicate-count by shared-identity interaction is absent under matched positions or if inspection mediation does not explain the success loss; preserve E3 as the surviving alternative. Require a simultaneous 95% interval excluding a 5-point success effect for the null-equivalence decision; expected 8–12-point signal comes from the independent E1/E2 observations. Report all null outcomes. No proposed repair arm is included.
Why It May Be Novel: E1/E2 occupy the anomaly, E5 occupies generic double-counting, and E3 occupies an alternative interpretation. The new contribution is a decisive explanation test in frozen closed-loop retrieval agents where E6 establishes sufficient control; neither anomaly repetition nor familiar Bayesian terminology is counted as payoff.
''', '''
E1 — Duplicate Log Study. In this hypothetical record, full methods and preregistered tables report 12-point lower success after exact event duplicates, with identical unique observations and token budgets across 20 tasks. Intervals exclude zero. Code and frozen checkpoints are supplied. Positions were not matched; the cause was not identified.
E2 — Independent Replication. Full methods independently report an 8-point decrease under the same information-preserving duplication on another memory architecture. It controls token count and observation accuracy; it also leaves positions confounded.
E3 — Recency Explanation. Full methods show that shifting relevant items later in the prompt can alter inspection choices and success, without any duplicated evidence. It supplies a concrete competing causal account of E1/E2.
E4 — Strongest Retrieval Policy. Complete benchmark tables identify the strongest matched-budget baseline; frozen checkpoints allow input-level interventions without retraining. Its confidence and inspection actions are externally logged.
E5 — Correlated Evidence Theory. Full methods show that treating correlated observations as independent inflates confidence. This occupies the general mechanism, but does not establish that the agents in E1/E2 actually perform such counting or that it mediates their decisions.
E6 — Intervention Support Audit. Full methods verify independent control of evidence identity, duplicate positions, time stamps, token filler and inspection action in the same benchmark. Randomized intervention checks leave unique observations and pre-intervention trajectories unchanged. No duplicate-count by identity factorial test has been performed.
Strongest Counterexample: E5 already predicts miscalibration under double-counting. The unknown is whether this mechanism or E3's recency mechanism explains E1/E2 in actual closed-loop agents. E1/E2's published anomaly cannot itself count as this proposal's new payoff.
Overlap: high for the anomaly and generic mechanism; low for the specified discriminating explanation and attribution experiment in the closed hypothetical universe.
Papers Read: 6 synthetic full-method records.
''', {'primary':'Do not impose a blanket diagnostic ceiling solely because there is no repair arm. Evaluate the strong aligned prior and new discriminating explanation separately from the already occupied anomaly. A sound lowered verdict must identify insufficient remaining payoff or experimental weakness.', 'forbidden_rationale':['No repair arm automatically forbids Strong Accept','The previously observed anomaly itself counts as the new contribution'], 'may_still_fail':'A concrete supported argument that causal separation is routine or insufficiently valuable can still cap the candidate.'}),
]

expectations = []
for key, name, candidate, prior, expected in CASES:
    if prior is None:
        prior = CASES[0][3]
    directory = ROOT/'frozen'/key
    directory.mkdir(parents=True, exist_ok=True)
    (directory/'candidate.json').write_text(json.dumps({'candidate_id':'I1','candidate_markdown':candidate},ensure_ascii=False,sort_keys=True,separators=(',',':'))+'\n')
    prior = re.sub(r'^(E[1-6]) — ',lambda m:m.group(1)+' | https://synthetic.invalid/'+key+'/'+m.group(1)+' — ',prior,flags=re.M)
    prior = prior.replace('Papers Read: 6 synthetic full-method records.','Papers Read: 6\nRecord Type: synthetic full-method premises, not actual papers.')
    (directory/'prior_work.md').write_text(HEADER+prior)
    expectations.append({'key':key,'kind':name,'synthetic':True,**expected})
(ROOT/'synthetic-expectations.json').write_text(json.dumps(expectations,ensure_ascii=False,indent=2)+'\n')
print('Prepared four synthetic conditional packets; no provider calls.')
